### ISSUE TITLE
Cannot export TailwindComponent

### ISSUE THREAD

**Issue by taylor-ben** [MathiasGilson/Tailwind-Styled-Component#38] opened 2022-01-17 10:58 UTC
Cannot export a component

```tsx
export const MyContainer = tw.div`flex`
```

Getting this error:
`Exported variable 'Container' has or is using name 'TailwindComponent' from external module ".../node_modules/tailwind-styled-components/dist/tailwind" but cannot be named.ts(4023)`

**Comment by taylor-ben** [comment] 2022-01-17 11:04
Suggestion:

`./src/tailwind.tsx`
```tsx
export interface TailwindComponent
```

**Comment by Oldbury** [comment] 2022-01-17 18:44
I'm getting this too, following for updates

**Comment by MathiasGilson** [comment] 2022-01-18 21:47
Hello guys, 

I could not reproduce on my test repo.
Could you share your typescript version and your tsconfig.js ?

Many thanks

**Comment by MathiasGilson** [comment] 2022-01-18 22:35
Okay I was able to reproduce, this was indeed due to not exporting the interface TailwindComponent.
It's now fixed in the version 2.1.1

thanks for reporting this issue!

**Closed by MathiasGilson** 2022-01-18 22:35 UTC
